"""Declarative base class shared by all ORM models."""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# A fixed naming convention for constraints and indexes. Without it, the
# database picks names on its own (for example "chunks_document_id_fkey"),
# which differ by database and make Alembic's autogenerated migrations
# harder to read and to diff.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models. Every model inherits from this."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
